version: "3"
volumes:
  mongodb_data:

services:
  url_shortener-mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=url_shortener
      - MONGO_INITDB_ROOT_PASSWORD=url_shortener
    volumes:
      - mongodb_data:/bitnami/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  url_shortener-mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - url_shortener-mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=url_shortener-mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=123
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=url_shortener
      - ME_CONFIG_MONGODB_ADMINPASSWORD=url_shortener
